### ISSUE TITLE
Fill-up series Repo on DS-Algo

### ISSUE THREAD

**Issue by SamarjeetBanik** [SamarjeetBanik/get-your-PR-accepted#1]
Hello Contributors! [This repo](https://github.com/SamarjeetBanik/get-your-PR-accepted) needs your contribution to fill up the DS-Algo problems mentioned. Your contribution can help a whole lot of students in learning DS-Algo.

### Please go through the **_README.md_** texts, present in each and every folder for understanding of the rules, in order to contribute. This would help you in getting a successful merge to your PR.

**Comment by ShlokMohanty** [comment]
@SamarjeetBanik can i take on this issue ?

**Comment by SamarjeetBanik** [comment]
Yes, ofcourse! It's open to all!

**Comment by ShlokMohanty** [comment]
ok thanks for the confirmation @SamarjeetBanik

**Comment by newbiens** [comment]
I have contributed, please look into that

**Comment by SamarjeetBanik** [comment]
Ya, reviewed! Thanks for your contribution. Really appreciate your contribution!

**Comment by monubucky** [comment]
I have contributed ,Please acknowledge it

**Comment by SamarjeetBanik** [comment]
I have commented on your PR @monubucky, kindly fulfill that criteria, in order to get your PR accepted.

**Comment by monubucky** [comment]
I have change as per request,kindly accept request

**Comment by SamarjeetBanik** [comment]
Ya, reviewed and accepted! Thanks for your contribution.

**Comment by SamarjeetBanik** [comment]
Thanks for all your contribution! I am closing this issue here.

# P.S.: This repo is violating the guidelines of Hacktoberfest 2021.
