### ISSUE TITLE
Design of Helical Springs - Python program

### ISSUE THREAD

**Issue by mugdhapendse** [SamarjeetBanik/get-your-PR-accepted#101]
Anyone, even from a non-technical background can obtain the design parameters of a helical spring by giving inputs like maximum weight attached, length of scale, spring index.

It'd be great if I could contribute to this under hacktoberfest tag.

**Comment by SamarjeetBanik** [comment]
Yes @mugdhapendse! Go ahead, you are free to contribute and welcome, if all the criteria for a successful PR is satisfied. 😄
