### ISSUE TITLE
Want to add bubble sort in sorting algo section

### ISSUE THREAD

**Issue by SahityaRoy** [SamarjeetBanik/get-your-PR-accepted#3]
Hey please consider my issue in hacktoberfest2021 , i want to add bubble sort in java.
Thank You

**Comment by SamarjeetBanik** [comment]
It is a conflicting file, because it is totally copied from some internet vendor. Kindly look into it.

**Comment by mohitsharma2635** [comment]
please add me i can code bubble sort in c

**Comment by purohitmansi** [comment]
Please do assign this to me.
